name: Test placeholder
on:
  push:
    branches:
      - develop
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build 
    runs-on: ubuntu-20.04
    env:
      CI: "true"
    steps:
    - id: checkout
      name: Check out source code
      uses: actions/checkout@v2

    - id: ack
      name: Ack flow
      run: |-
        echo "ack recv"
