name: Test placeholder
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    name: Build 
    runs-on: ubuntu-20.04
    if: |-
      !github.event.pull_request == true || 
      startsWith(github.event.pull_request.head.ref, 'release/') ||
      startsWith(github.event.pull_request.head.ref, 'hotfix/') 
    env:
      CI: "true"
    steps:
    - id: checkout
      name: Check out source code
      uses: actions/checkout@v2

    - id: ack
      name: Ack flow
      run: |-
        echo "ack recv"
